name: chart_app
description: Chart App
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.16.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    deriv_chart:
        path: ../../flutter-chart
    js: ^0.6.7

dev_dependencies:
    deriv_lint:
        git:
            url: git@github.com:regentmarkets/flutter-deriv-packages.git
            path: packages/deriv_lint
            ref: dev
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
